### ISSUE TITLE
4 Channel Image Support

### ISSUE THREAD

**Issue by dchun** [dfdx/PiecewiseAffineTransforms.jl#1]
All image rendering functions appear to generate a similar issue when a four channel image is generated from the Image package.

A sample error from the `triplot()` function:

```
ERROR: Cannot infer colorspace of Array, use an AbstractImage type
 in colorspace at /Users/davidchun/.julia/v0.3/Images/src/core.jl:684
 in properties at /Users/davidchun/.julia/v0.3/Images/src/core.jl:625
 in triplot at /Users/davidchun/.julia/v0.3/PiecewiseAffineTransforms/src/view.jl:15
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/davidchun/.julia/v0.3/PiecewiseAffineTransforms/examples/ex.jl, in expression starting on line 41
```

Is this perhaps a deeper issue with determining why my environment is generating a four channel image than to force a three channel image in the package?

**Comment by dfdx** [comment]
From [this](https://github.com/timholy/Images.jl/issues/353) issue it becomes clear why you get a 4-channel image instead of a 3-channel one. In general, 4-channel image is legal, so it would be nice to support it here. However, proper way to implement it would be to use image types instead of plain arrays, which is quite a huge change and is not a priority number 1 for now. 

As a quick fix, I've updated FaceDatasets.jl (which you probably used to get example image) to force 3-dimensions, regardless of the platform. This change is already in FaceDataset's master and soon will be in tagged version, so you can give it a try.

**Comment by dchun** [comment]
That seems to do the trick. I also modified a function in the example script in pull request #2

**Comment by dfdx** [comment]
Ah, I missed this one. Thanks!
