### ISSUE TITLE
ImageView dependency

### ISSUE THREAD

**Issue by Evizero** [dfdx/PiecewiseAffineTransforms.jl#4]
Is there any chance I could convince you to remove the image view dependency? I intend to use your cool package as a backend for an image augmentation library I am working on (basically to emulate elastic distortions; see image below), and the having ImageView in there makes some stuff a bit tedious (such as travis testing), and it also kinda feels weird.

One proposal I would have is to use https://github.com/JuliaPlots/RecipesBase.jl instead, which is a lightweight package that allows to specify custom plots that can then be used with the Plots.jl package

This is an example of how my recipes for plotting the triangles currently look:

<img width="573" alt="displacement" src="https://cloud.githubusercontent.com/assets/10854026/17462602/5078e99c-5cb2-11e6-89ea-946d51f311df.png">

The only current problem with `RecipesBase` is that it doesn't yet allow to specify custom plot name (such as `triplot`) but require a custom type. But I have talked to @tbreloff about it and this may be added in the future

What do you think about this in general?

**Comment by Evizero** [comment]
Also note that I would be more than willing to do the actual coding. I am **not** asking you to spend your time on this. I am just curious about your stance on this.

**Comment by dfdx** [comment]
I definitely support removing heavy dependencies, however since `triplot` is an exported function and other packages may already use it (one of my own packages does, for example), it would be nice to (more or less) keep backward compatibility. One easy way that comes to mind is to remove entry from REQUIRE, but leave definition of `triplot` _conditional on_ ImageView.jl being installed. I.e. something like: 

```
if Pkg.installed("ImageView") != nothing 
    function triplot()
       ...
    end
end
```

We may additionally provide alternative `triplot` for cases when ImageView isn't installed and user still wants to visualize triangulation, but that's another story and may be implemented later. 

Does it sound reasonable for you?

**Comment by Evizero** [comment]
love it! I'll code this up soon
